services:
  bot:
    image: 52lxcloud/newrelease:latest
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=机器人token
      - ADMIN_ID=管理员ID
      - GITHUB_TOKEN=githubtoken
    volumes:
      - ./data:/data
